#!/bin/bash
set -eEu
set -o pipefail

docker build --rm -t builder src/

cat > ci/vars <<EOF
export VERSION=$(docker run --rm -it --entrypoint ruby builder -e 'load "lib/autostager/version.rb"; print Autostager::VERSION')
EOF
. ci/vars
