#!/bin/sh
set -eu
set -o pipefail

mkdir -p ~/.gem/ || :
cp -f credentials ~/.gem/
chmod 0600 ~/.gem/credentials
sed -i "s/API_KEY/${API_KEY}/" ~/.gem/credentials

VERSION="$(ruby -e 'load "lib/autostager/version.rb"; print Autostager::VERSION')"
echo "VERSION is ${VERSION}"
output="$(gem search --remote -a puppet-autostager)"
if echo "${output}" | grep -q  "${VERSION}"; then
  # Be informative, but don't fail.
  # This enables to merge changes to non-gem files, such as README.
  echo "puppet-autostager ${VERSION} has already been published."
else
  gem push "puppet-autostager-${VERSION}.gem"
fi
